INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('bactery_waterBottle', 'Botella de agua con bacterias', -1, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('blueberry_fruit', 'Arándano', 50, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('blueberry_package', 'Caja de arándanos', -1, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('blueberry_seed', 'Semilla de Arándanos', 10, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('bottleWater_package', 'Caja de Botellas de Agua', -1, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('carbon_piece', 'Trozo de carbón', 50, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('dirty_waterBottle', 'Botella de agua sucia', -1, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('fertilizer_25', 'Fertilizante de 25', 5, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('fertilizer_50', 'Fertilizante de 50', 5, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('full_waterBottle', 'Botella de agua pura', -1, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('gold_piece', 'Pepita de oro', 50, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('iron_piece', 'Fragmento de hierro', 50, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('lingot_carbon', 'Carbón procesado', 50, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('lingot_gold', 'Lingote de oro', 50, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('lingot_iron', 'Lingote de hierro', 50, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('lingot_silver', 'Lingote de plata', 50, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('pine_processed', 'Madera de pino procesada', 10, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('pine_wood', 'Madera de pino', 50, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('pollution_waterBottle', 'Botella de agua contaminada', -1, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('salt_waterBottle', 'Botella de agua salada', -1, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('tomato_fruit', 'Tomate', -1, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('tomato_package', 'Caja de Tomates', -1, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('tomato_seed', 'Semilla de Tomate', -1, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('toxic_waterBottle', 'Botella de agua toxica', -1, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('waterBottle', 'Botella de agua', -1, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('water_25', 'Garrafa de 25 litros', 5, 0, 1);
INSERT INTO `poplife`.`items`(`name`, `label`, `limit`, `rare`, `can_remove`) VALUES ('water_50', 'Garrafa de 50 litros', 5, 0, 1);
