itemList = {}

-- 250kg limit on player

--Weapons
itemList["WEAPON_ADVANCEDRIFLE"] = {name = "WEAPON_ADVANCEDRIFLE", id = "WEAPON_ADVANCEDRIFLE", itemId = "WEAPON_ADVANCEDRIFLE", label = "ADVANCED RIFLE" , rare = false, weight = 7, canRemove = true, isWeapon = true, description = "5.56 mm death machine", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_APPISTOL"] = {name = "WEAPON_APPISTOL", id = "WEAPON_APPISTOL", itemId = "WEAPON_APPISTOL", label = "AP PISTOL" , rare = false, weight = 6, canRemove = true, isWeapon = true, description = "Causing mass panic in a small package", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_ASSUALTRIFLE"] = {name = "WEAPON_ASSUALTRIFLE", id = "WEAPON_ASSUALTRIFLE", itemId = "WEAPON_ASSUALTRIFLE", label = "ASSAULT RIFLE" , rare = false, weight = 9, canRemove = true, isWeapon = true, description = "In Soviet Russia gun shoots you!", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_ASSUALTSMG"] = {name = "WEAPON_ASSUALTSMG", id = "WEAPON_ASSUALTSMG", itemId = "WEAPON_ASSUALTSMG", label = "ASSAULT SMG" , rare = false, weight = 4, canRemove = true, isWeapon = true, description = "What?! Youse still this from NOOSE?", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_AUTOSHOTGUN"] = {name = "WEAPON_AUTOSHOTGUN", id = "WEAPON_AUTOSHOTGUN", itemId = "WEAPON_AUTOSHOTGUN", label = "AUTO SHOTGUN" , rare = false, weight = 10, canRemove = true, isWeapon = true, description = "Close quaters? Need to shoot 300 RPM? This'll do lad.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_BALL"] = {name = "WEAPON_BALL", id = "WEAPON_BALL", itemId = "WEAPON_BALL", label = "BALL" , rare = false, weight = 1, canRemove = true, isWeapon = true, description = "I'm assuming this is a baseball. I really hope so. If not, this is awkward.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_BAT"] = {name = "WEAPON_BAT", id = "WEAPON_BAT", itemId = "WEAPON_BAT", label = "BAT" , rare = false, weight = 3, canRemove = true, isWeapon = true, description = "Sure you could hit a baseball with this but hearing the crack of a skull is so much better.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_BATTLEAXE"] = {name = "WEAPON_BATTLEAXE", id = "WEAPON_BATTLEAXE", itemId = "WEAPON_BATTLEAXE", label = "BATTLE AXE" , rare = false, weight = 7, canRemove = true, isWeapon = true, description = "Just don't let it fall of you.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_BOTTLE"] = {name = "WEAPON_BOTTLE", id = "WEAPON_BOTTLE", itemId = "WEAPON_BOTTLE", label = "BOTTLE" , rare = false, weight = 1, canRemove = true, isWeapon = true, description = "A good tool for a drunken fight in a bar.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_BULLPUPRIFLE"] = {name = "WEAPON_BULLPUPRIFLE", id = "WEAPON_BULLPUPRIFLE", itemId = "WEAPON_BULLPUPRIFLE", label = "BULLPUP RIFLE" , rare = false, weight = 8, canRemove = true, isWeapon = true, description = "The lighest rifle around.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_BULLPUPSHOTGUN"] = {name = "WEAPON_BULLPUPSHOTGUN", id = "WEAPON_BULLPUPSHOTGUN", itemId = "WEAPON_BULLPUPSHOTGUN", label = "BULLPUP SHOTGUN", rare = false, weight = 7, canRemove = true, isWeapon = true, description = "It's good gun, yes?", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_BZGAS"] = {name = "WEAPON_BZGAS", id = "WEAPON_BZGAS", itemId = "WEAPON_BZGAS", label = "BZ GAS" , rare = false, weight = 1, canRemove = true, isWeapon = true, description = "*Coughing noises*", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_CARBINERIFLE"] = {name = "WEAPON_CARBINERIFLE", id = "WEAPON_CARBINERIFLE", itemId = "WEAPON_CARBINERIFLE", label = "CARBINE RIFLE" , rare = false, weight = 8, canRemove = true, isWeapon = true, description = "The backbone of the US military.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_COMBATMG"] = {name = "WEAPON_COMBATMG", id = "WEAPON_COMBATMG", itemId = "WEAPON_COMBATMG", label = "COMBAT MG" , rare = false, weight = 18, canRemove = true, isWeapon = true, description = "It's got the firepower, you just need the ammo.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_COMBATPDW"] = {name = "WEAPON_COMBATPDW", id = "WEAPON_COMBATPDW", itemId = "WEAPON_COMBATPDW", label = "COMBAT PDW" , rare = false, weight = 7, canRemove = true, isWeapon = true, description = "The best way to defend oneself.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_COMBATPISTOL"] = {name = "WEAPON_COMBATPISTOL", id = "WEAPON_COMBATPISTOL", itemId = "WEAPON_COMBATPISTOL", label = "COMBAT PISTOL", rare = false, weight = 1, canRemove = true, isWeapon = true, description = "The Germans know how to make a pistol.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_COMPACTLAUNCHER"] = {name = "WEAPON_COMPACTLAUNCHER", id = "WEAPON_COMPACTLAUNCHER", itemId = "WEAPON_COMPACTLAUNCHER", label = "COMPACT LAUNCHER", rare = false, weight = 7, canRemove = true, isWeapon = true, description = "Point, look, kaboom.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_COMPACTRIFLE"] = {name = "WEAPON_COMPACTRIFLE", id = "WEAPON_COMPACTRIFLE", itemId = "WEAPON_COMPACTRIFLE", label = "COMPACT RIFLE", rare = false, weight = 5, canRemove = true, isWeapon = true, description = "A good compact way of solving any problem.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_CROWBAR"] = {name = "WEAPON_CROWBAR", id = "WEAPON_CROWBAR", itemId = "WEAPON_CROWBAR", label = "CROWBAR", rare = false, weight = 3, canRemove = true, isWeapon = true, description = "Allowing illegal activities since the 1400s.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_DAGGER"] = {name = "WEAPON_DAGGER", id = "WEAPON_DAGGER", itemId = "WEAPON_DAGGER", label = "DAGGER" , rare = false, weight = 2, canRemove = true, isWeapon = true, description = "A great way to stab oneself.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_DBSHOTGUN"] = {name = "WEAPON_DBSHOTGUN", id = "WEAPON_DBSHOTGUN", itemId = "WEAPON_DBSHOTGUN", label = "DOUBLE BARREL SHOTGUN", rare = false, weight = 7, canRemove = true, isWeapon = true, description = "Shoot twice and reload quick!", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_DIGISCANNER"] = {name = "WEAPON_DIGISCANNER", id = "WEAPON_DIGISCANNER", itemId = "WEAPON_DIGISCANNER", label = "DIGGISCANNER", rare = false, weight = 3, canRemove = true, isWeapon = true, description = "No idea what this is but I'm sure it scans.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_DOUBLEACTION"] = {name = "WEAPON_DOUBLEACTION", id = "WEAPON_DOUBLEACTION", itemId = "WEAPON_DOUBLEACTION", label = "DOUBLE ACTION REVOLVER", rare = false, weight = 5, canRemove = true, isWeapon = true, description = "Cowboys used it.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_FIREEXTINGUISHER"] = {name = "WEAPON_FIREEXTINGUISHER", id = "WEAPON_FIREEXTINGUISHER", itemId = "WEAPON_FIREEXTINGUISHER", label = "FIRE EXTINGUISHER" , rare = false, weight = 5, canRemove = true, isWeapon = true, description = "Fights Fire.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_FIREWORK"] = {name = "WEAPON_FIREWORK", id = "WEAPON_FIREWORK", itemId = "WEAPON_FIREWORK", label = "FIREWORK" , rare = false, weight = 5, canRemove = true, isWeapon = true, description = "Cos baby you're a fireeeeeework!", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_FLARE"] = {name = "WEAPON_FLARE", id = "WEAPON_FLARE", itemId = "WEAPON_FLARE", label = "FLARE" , rare = false, weight = 1, canRemove = true, isWeapon = true, description = "Take some of these flares.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_FLAREGUN"] = {name = "WEAPON_FLAREGUN", id = "WEAPON_FLAREGUN", itemId = "WEAPON_FLAREGUN", label = "FLAREGUN" , rare = false, weight = 1, canRemove = true, isWeapon = true, description = "Alright General, with this flaregun you can call in nearby minutemen to help.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_FLASHLIGHT"] = {name = "WEAPON_FLASHLIGHT", id = "WEAPON_FLASHLIGHT", itemId = "WEAPON_FLASHLIGHT", label = "FLASHLIGHT" , rare = false, weight = 2, canRemove = true, isWeapon = true, description = "Not to be confused with a fleshlight.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_GARBAGEBAG"] = {name = "WEAPON_GARBAGEBAG", id = "WEAPON_GARBAGEBAG", itemId = "WEAPON_GARBAGEBAG", label = "GARBAGE BAG" , rare = false, weight = 3, canRemove = true, isWeapon = true, description = "Cover your nose!", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_GOLFCLUB"] = {name = "WEAPON_GOLFCLUB", id = "WEAPON_GOLFCLUB", itemId = "WEAPON_GOLFCLUB", label = "GOLF CLUB" , rare = false, weight = 1, canRemove = true, isWeapon = true, description = "Usually used to hit a golf ball, but you can hit balls with it still.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_GRENADELAUNCHER"] = {name = "WEAPON_GRENADELAUNCHER", id = "WEAPON_GRENADELAUNCHER", itemId = "WEAPON_GRENADELAUNCHER", label = "GRENADE LAUNCHER" , rare = false, weight = 13.2, canRemove = true, isWeapon = true, description = "Just like the compact version but with more joy.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_GUNSENBERG"] = {name = "WEAPON_GUNSENBERG", id = "WEAPON_GUNSENBERG", itemId = "WEAPON_GUNSENBERG", label = "GUNSENBERG" , rare = false, weight = 10, canRemove = true, isWeapon = true, description = "You just call me Scarface", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_HAMMER"] = {name = "WEAPON_HAMMER", id = "WEAPON_HAMMER", itemId = "WEAPON_HAMMER", label = "HAMMER" , rare = false, weight = 1, canRemove = true, isWeapon = true, description = "Stop. Hammer time,", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_HANDCUFFS"] = {name = "WEAPON_HANDCUFFS", id = "WEAPON_HANDCUFFS", itemId = "WEAPON_HANDCUFFS", label = "HANDCUFFS" , rare = false, weight = 1, canRemove = true, isWeapon = true, description = "You've been bad. Very, very bad.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_HATCHET"] = {name = "WEAPON_HATCHET", id = "WEAPON_HATCHET", itemId = "WEAPON_HATCHET", label = "HATCHET" , rare = false, weight = 3, canRemove = true, isWeapon = true, description = "Slash and hack.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_HEAVYPISTOL"] = {name = "WEAPON_HEAVYPISTOL", id = "WEAPON_HEAVYPISTOL", itemId = "WEAPON_HEAVYPISTOL", label = "HEAVY PISTOL" , rare = false, weight = 5, canRemove = true, isWeapon = true, description = "Pew pew.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_HEAVYSHOTGUN"] = {name = "WEAPON_HEAVYSHOTGUN", id = "WEAPON_HEAVYSHOTGUN", itemId = "WEAPON_HEAVYSHOTGUN", label = "HEAVY SHOTGUN" , rare = false, weight = 15, canRemove = true, isWeapon = true, description = "Boomstick.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_HEAVYSNIPER"] = {name = "WEAPON_HEAVYSNIPER", id = "WEAPON_HEAVYSNIPER", itemId = "WEAPON_HEAVYSNIPER", label = "HEAVY SNIPER RIFLE" , rare = false, weight = 35, canRemove = true, isWeapon = true, description = "In my sights.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_HOMINGLAUNCHER"] = {name = "WEAPON_HOMINGLAUNCHER", id = "WEAPON_HOMINGLAUNCHER", itemId = "WEAPON_HOMINGLAUNCHER", label = "HOMING LAUNCHER" , rare = false, weight = 35, canRemove = true, isWeapon = true, description = "Seek and destroy.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_KNIFE"] = {name = "WEAPON_KNIFE", id = "WEAPON_KNIFE", itemId = "WEAPON_KNIFE", label = "KNIFE" , rare = false, weight = 3, canRemove = true, isWeapon = true, description = "You wanna know how I got these scars?", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_KNUCKLE"] = {name = "WEAPON_KNUCKLE", id = "WEAPON_KNUCKLE", itemId = "WEAPON_KNUCKLE", label = "KNUCKLE DUSTER" , rare = false, weight = 1, canRemove = true, isWeapon = true, description = "Administer a mouthful of fist.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_MACHETE"] = {name = "WEAPON_MACHETE", id = "WEAPON_MACHETE", itemId = "WEAPON_MACHETE", label = "MACHETE" , rare = false, weight = 3, canRemove = true, isWeapon = true, description = "Not just for the jungle anymore.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_MACHINEPISTOL"] = {name = "WEAPON_MACHINEPISTOL", id = "WEAPON_MACHINEPISTOL", itemId = "WEAPON_MACHINEPISTOL", label = "MACHINE PISTOL" , rare = false, weight = 4, canRemove = true, isWeapon = true, description = "No drive-by sounds quite right without it.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_MARKSMANRIFLE"] = {name = "WEAPON_MARKSMANRIFLE", id = "WEAPON_MARKSMANRIFLE", itemId = "WEAPON_MARKSMANRIFLE", label = "MARKSMAN RIFLE" , rare = false, weight = 12, canRemove = true, isWeapon = true, description = "There is no escaping once you're in my crosshair.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_MG"] = {name = "WEAPON_MG", id = "WEAPON_MG", itemId = "WEAPON_MG", label = "MG" , rare = false, weight = 15, canRemove = true, isWeapon = true, description = "Very effective against large groups.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_MICROSMG"] = {name = "WEAPON_MICROSMG", id = "WEAPON_MICROSMG", itemId = "WEAPON_MICROSMG", label = "MICRO SMG" , rare = false, weight = 4, canRemove = true, isWeapon = true, description = "May be small, but it shreads.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_MINIGUN"] = {name = "WEAPON_MINIGUN", id = "WEAPON_MINIGUN", itemId = "WEAPON_MINIGUN", label = "MINIGUN" , rare = false, weight = 35, canRemove = true, isWeapon = true, description = "Say hello to my little friend!", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_MINISMG"] = {name = "WEAPON_MINISMG", id = "WEAPON_MINISMG", itemId = "WEAPON_MINISMG", label = "MINI SMG" , rare = false, weight = 4, canRemove = true, isWeapon = true, description = "Small and powerful.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_MOLOTOV"] = {name = "WEAPON_MOLOTOV", id = "WEAPON_MOLOTOV", itemId = "WEAPON_MOLOTOV", label = "MOLOTOV" , rare = false, weight = 1, canRemove = true, isWeapon = true, description = "Light and throw.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_MUSKET"] = {name = "WEAPON_MUSKET", id = "WEAPON_MUSKET", itemId = "WEAPON_MUSKET", label = "MUSKET" , rare = false, weight = 8, canRemove = true, isWeapon = true, description = "Don't miss. It takes a while to reload.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_NIGHTSTICK"] = {name = "WEAPON_NIGHTSTICK", id = "WEAPON_NIGHTSTICK", itemId = "WEAPON_NIGHTSTICK", label = "NIGHTSTICK" , rare = false, weight = 3, canRemove = true, isWeapon = true, description = "Stop resisting!", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_PETROLCAN"] = {name = "WEAPON_PETROLCAN", id = "WEAPON_PETROLCAN", itemId = "WEAPON_PETROLCAN", label = "PETROL CAN" , rare = false, weight = 5, canRemove = true, isWeapon = true, description = "Fill it with fuel.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_PIPEBOMB"] = {name = "WEAPON_PIPEBOMB", id = "WEAPON_PIPEBOMB", itemId = "WEAPON_PIPEBOMB", label = "PIPE BOMB" , rare = false, weight = 3, canRemove = true, isWeapon = true, description = "Homemade destruction.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_PISTOL"] = {name = "WEAPON_PISTOL", id = "WEAPON_PISTOL", itemId = "WEAPON_PISTOL", label = "PISTOL" , rare = false, weight = 20, canRemove = true, isWeapon = true, description = "Aim. Shoot.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_PISTOL50"] = {name = "WEAPON_PISTOL50", id = "WEAPON_PISTOL50", itemId = "WEAPON_PISTOL50", label = "PISTOL.50" , rare = false, weight = 7, canRemove = true, isWeapon = true, description = "High caliber pistol.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_POOLCUE"] = {name = "WEAPON_POOLCUE", id = "WEAPON_POOLCUE", itemId = "WEAPON_POOLCUE", label = "POOL CUE" , rare = false, weight = 2, canRemove = true, isWeapon = true, description = "Good at knocking balls around.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_PROXMINE"] = {name = "WEAPON_PROXMINE", id = "WEAPON_PROXMINE", itemId = "WEAPON_PROXMINE", label = "PROXIMITY MINE" , rare = false, weight = 1, canRemove = true, isWeapon = true, description = "Don't stand so close to me.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_PUMPSHOTGUN"] = {name = "WEAPON_PUMPSHOTGUN", id = "WEAPON_PUMPSHOTGUN", itemId = "WEAPON_PUMPSHOTGUN", label = "PUMP SHOTGUN" , rare = false, weight = 10, canRemove = true, isWeapon = true, description = "Click Clik Boom.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_RAILGUN"] = {name = "WEAPON_RAILGUN", id = "WEAPON_RAILGUN", itemId = "WEAPON_RAILGUN", label = "RAILGUN" , rare = false, weight = 35, canRemove = true, isWeapon = true, description = "It does horrible things to the things it's pointed at.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_REVOLVER"] = {name = "WEAPON_REVOLVER", id = "WEAPON_REVOLVER", itemId = "WEAPON_REVOLVER", label = "REVOLVER" , rare = false, weight = 6, canRemove = true, isWeapon = true, description = "6 shots? I only need 1.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_RPG"] = {name = "WEAPON_RPG", id = "WEAPON_RPG", itemId = "WEAPON_RPG", label = "RPG" , rare = false, weight = 20, canRemove = true, isWeapon = true, description = "Very effective.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_SAWNOFFSHOTGUN"] = {name = "WEAPON_SAWNOFFSHOTGUN", id = "WEAPON_SAWNOFFSHOTGUN", itemId = "WEAPON_SAWNOFFSHOTGUN", label = "SAWED-OFF SHOTGUN" , rare = false, weight = 4, canRemove = true, isWeapon = true, description = "Devastating efficiency in close combat.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_SMG"] = {name = "WEAPON_SMG", id = "WEAPON_SMG", itemId = "WEAPON_SMG", label = "SMG" , rare = false, weight = 5, canRemove = true, isWeapon = true, description = "Shoots fast.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_SMOKEGRENADE"] = {name = "WEAPON_SMOKEGRENADE", id = "WEAPON_SMOKEGRENADE", itemId = "WEAPON_SMOKEGRENADE", label = "SMOKE GRENADE" , rare = false, weight = 1, canRemove = true, isWeapon = true, description = "Ninja vanish!", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_SNIPERRIFLE"] = {name = "WEAPON_SNIPERRIFLE", id = "WEAPON_SNIPERRIFLE", itemId = "WEAPON_SNIPERRIFLE", label = "SNIPER RIFLE" , rare = false, weight = 20, canRemove = true, isWeapon = true, description = "Kill from a distance.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_SNOWBALL"] = {name = "WEAPON_SNOWBALL", id = "WEAPON_SNOWBALL", itemId = "WEAPON_SNOWBALL", label = "SNOWBALL" , rare = false, weight = 1, canRemove = true, isWeapon = true, description = "Watch out for the yellow ones.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_SNSPISTOL"] = {name = "WEAPON_SNSPISTOL", id = "WEAPON_SNSPISTOL", itemId = "WEAPON_SNSPISTOL", label = "SNS PISTOL" , rare = false, weight = 3, canRemove = true, isWeapon = true, description = "Fits in your pocket for a night on the town.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_SPECIALCARBINE"] = {name = "WEAPON_SPECIALCARBINE", id = "WEAPON_SPECIALCARBINE", itemId = "WEAPON_SPECIALCARBINE", label = "SPECIAL CARBINE" , rare = false, weight = 8, canRemove = true, isWeapon = true, description = "Extremely versatile assault rifle for any combat situation.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_STICKYBOMB"] = {name = "WEAPON_STICKYBOMB", id = "WEAPON_STICKYBOMB", itemId = "WEAPON_STICKYBOMB", label = "STICKY BOMB" , rare = false, weight = 3, canRemove = true, isWeapon = true, description = "Stick it then leave it.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_STINGER"] = {name = "WEAPON_STINGER", id = "WEAPON_STINGER", itemId = "WEAPON_STINGER", label = "STINGER" , rare = false, weight = 15, canRemove = true, isWeapon = true, description = "", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_STUNGUN"] = {name = "WEAPON_STUNGUN", id = "WEAPON_STUNGUN", itemId = "WEAPON_STUNGUN", label = "POLICE TASER" , rare = false, weight = 5, canRemove = true, isWeapon = true, description = "It's shocking.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_SWITCHBLADE"] = {name = "WEAPON_SWITCHBLADE", id = "WEAPON_SWITCHBLADE", itemId = "WEAPON_SWITCHBLADE", label = "SWITCHBLADE" , rare = false, weight = 2, canRemove = true, isWeapon = true, description = "Folding knives will never go out of style.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_VINTAGEPISTOL"] = {name = "WEAPON_VINTAGEPISTOL", id = "WEAPON_VINTAGEPISTOL", itemId = "WEAPON_VINTAGEPISTOL", label = "VINTAGE PISTOL" , rare = false, weight = 5, canRemove = true, isWeapon = true, description = "Shoot in style.", closeonuse = false, useable = true, max = 1 }
itemList["WEAPON_WRENCH"] = {name = "WEAPON_WRENCH", id = "WEAPON_WRENCH", itemId = "WEAPON_WRENCH", label = "WRENCH" , rare = false, weight = 1, canRemove = true, isWeapon = true, description = "Tightening up loose ends.", closeonuse = false, useable = true, max = 1 }

--Foods 
itemList["5fromages"] = {name = "5fromages", id = "5fromages", itemId = "5fromages", label = "5 CHEESE PIZZA" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Cheese overload.", closeonuse = false, useable = true, max = 10}
itemList["barbecue"] = {name = "barbecue", id = "barbecue", itemId = "barbecue", label = "BARBECUE PIZZA" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Best of both worlds.", closeonuse = false, useable = true, max = 10}
itemList["bread"] = {name = "bread", id = "bread", itemId = "bread", label = "BREAD" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Yummy Food", closeonuse = false, useable = true, max = 15}
itemList["calzone"] = {name = "calzone", id = "calzone", itemId = "calzone", label = "PIZZA CALZONE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Folded pizza.", closeonuse = false, useable = true, max = 10}
itemList["chips"] = {name = "chips", id = "chips", itemId = "chips", label = "CHIPS" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Bet you can't eat just one.", closeonuse = false, useable = true, max = 5}
itemList["chocolate"] = {name = "chocolate", id = "chocolate", itemId = "chocolate", label = "CHOCOLATE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Melts in your mouth and not your hand.", closeonuse = false, useable = true, max = 10}
itemList["cupcake"] = {name = "cupcake", id = "cupcake", itemId = "cupcake", label = "CUPCAKE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Little cakes in a wrapper.", closeonuse = false, useable = true, max = 15}
itemList["hamburger"] = {name = "hamburger", id = "hamburger", itemId = "hamburger", label = "HAMBURGER" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Have it your way.", closeonuse = false, useable = true, max = 15}
itemList["jablka"] = {name = "jablka", id = "jablka", itemId = "jablka", label = "APPLES" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Keeps the doctor away.", closeonuse = false, useable = true, max = 40}
itemList["meat"] = {name = "meat", id = "meat", itemId = "meat", label = "MEAT" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "How do you like your meat?", closeonuse = false, useable = true, max = -1}
itemList["orientale"] = {name = "orientale", id = "orientale", itemId = "orientale", label = "ORIENTAL PIZZA" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "A little slice of the orient.", closeonuse = false, useable = true, max = 10}
itemList["pate"] = {name = "pate", id = "pate", itemId = "pate", label = "PIZZA DOUGH" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "A little slice of the orient.", closeonuse = false, useable = true, max = -1}
itemList["pomarancza"] = {name = "pomarancza", id = "pomarancza", itemId = "pomarancza", label = "ORANGES" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Give it a little squeeze.", closeonuse = false, useable = true, max = 40}
itemList["reine"] = {name = "reine", id = "reine", itemId = "reine", label = "QUEEN PIZZA" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Pizza", closeonuse = false, useable = true, max = 10}
itemList["sandwich"] = {name = "sandwich", id = "sandwich", itemId = "sandwich", label = "SANDWICH" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Bread, meat, eat.", closeonuse = false, useable = true, max = 15}
itemList["saumons"] = {name = "saumons", id = "saumons", itemId = "saumons", label = "SALMON PIZZA" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Salon flavored pizza.", closeonuse = false, useable = true, max = 10}
itemList["sportlunch"] = {name = "sportlunch", id = "sportlunch", itemId = "sportlunch", label = "SPORTLUNCH" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "High protein lunch.", closeonuse = false, useable = true, max = 15}

--Drinks
itemList["absinthe"] = {name = "absinthe", id = "absinthe", itemId = "absinthe", label = "ABSINTHE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Not your kids Koolaid.", closeonuse = false, useable = true, max = 5 }
itemList["beer"] = {name = "beer", id = "beer", itemId = "beer", label = "BEER" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Throw back a cold one.", closeonuse = false, useable = true, max = 15 }
itemList["champagne"] = {name = "champagne", id = "champagne", itemId = "champagne", label = "CHAMPAGNE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Bubbly", closeonuse = false, useable = true, max = 15 }
itemList["cocacola"] = {name = "cocacola", id = "cocacola", itemId = "cocacola", label = "COCA COLA" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Now made with real sugar!", closeonuse = false, useable = true, max = 10 }
itemList["coffe"] = {name = "coffe", id = "coffe", itemId = "coffe", label = "COFFEE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Filled with energy.", closeonuse = false, useable = true, max = 15 }
itemList["gintonic"] = {name = "gintonic", id = "gintonic", itemId = "gintonic", label = "GIN & TONIC" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Highball cocktail.", closeonuse = false, useable = true, max = 5 }
itemList["icetea"] = {name = "icetea", id = "icetea", itemId = "icetea", label = "ICE TEA" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Sweet and refreshing.", closeonuse = false, useable = true, max = 15 }
itemList["milk"] = {name = "milk", id = "milk", itemId = "milk", label = "MILK" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "It does a body good.", closeonuse = false, useable = true, max = 15 }
itemList["powerade"] = {name = "powerade", id = "powerade", itemId = "powerade", label = "POWERADE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Get back those electrolytes.", closeonuse = false, useable = true, max = 15 }
itemList["protein_shake"] = {name = "protein_shake", id = "protein_shake", itemId = "protein_shake", label = "PROTEIN SHAKE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "All about those gains.", closeonuse = false, useable = true, max = 15 }
itemList["sok"] = {name = "sok", id = "sok", itemId = "sok", label = "JUICE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Sell it or drink it.", closeonuse = false, useable = true, max = 80 }
itemList["tequila"] = {name = "tequila", id = "tequila", itemId = "tequila", label = "TEQUILA" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Don't drink the worm.", closeonuse = false, useable = true, max = 15 }
itemList["vodka"] = {name = "vodka", id = "vodka", itemId = "vodka", label = "VODKA" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "If Russia, vodka drinks you.", closeonuse = false, useable = true, max = 15 }
itemList["water"] = {name = "water", id = "water", itemId = "water", label = "WATER" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "High quality H20", closeonuse = false, useable = true, max = 20 }
itemList["waterBottle"] = {name = "waterBottle", id = "waterBottle", itemId = "waterBottle", label = "WATER BOTTLE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Water on the go.", closeonuse = false, useable = true, max = 15 }
itemList["whisky"] = {name = "whisky", id = "whisky", itemId = "whisky", label = "WHISKEY" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Straight from the casks.", closeonuse = false, useable = true, max = 15 }

--Useables
itemList["9mm_rounds"] = {name = "9mm_rounds", id = "9mm_rounds", itemId = "9mm_rounds", label = "9MM ROUNDS" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Ammo for your weapon.", closeonuse = false, useable = true, max = 20 }
itemList["advrepairkit"] = {name = "advrepairkit", id = "advrepairkit", itemId = "advrepairkit", label = "ADVANCED REPAIR KIT" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Everything is okay.", closeonuse = false, useable = true, max = 2 }
itemList["alive_chicken"] = {name = "alive_chicken", id = "alive_chicken", itemId = "alive_chicken", label = "CHICKEN" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Why did it cross the road?", closeonuse = false, useable = false, max = 10 }
itemList["alive_pig"] = {name = "alive_pig", id = "alive_pig", itemId = "alive_pig", label = "PIG" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Not to be confused with the Police.", closeonuse = false, useable = false, max = 10 }
itemList["arAmmo"] = {name = "arAmmo", id = "arAmmo", itemId = "arAmmo", label = "ASSAULT RIFLE AMMO" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Assault Rifle ammo.", closeonuse = false, useable = true, max = 5 }
itemList["armour"] = {name = "armour", id = "armour", itemId = "armour", label = "BODY ARMOR" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "It won't make you Deadpool, but it will keep you alive longer.", closeonuse = false, useable = true, max = 3 }
itemList["bagofdope"] = {name = "bagofdope", id = "bagofdope", itemId = "bagofdope", label = "WEED 1oz" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Hey. Want some weed?", closeonuse = false, useable = true, max = -1 }
itemList["bandage"] = {name = "bandage", id = "bandage", itemId = "bandage", label = "BANDAGE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "It won't make you Deadpool, but it will keep you alive longer.", closeonuse = false, useable = true, max = 10 }
itemList["bankidcard"] = {name = "bankidcard", id = "bankidcard", itemId = "bankidcard", label = "BANK ID CARD" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Seems important.", closeonuse = false, useable = true, max = -1 }
itemList["barrel"] = {name = "barrel", id = "barrel", itemId = "barrel", label = "BARREL" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "An empty barrel.", closeonuse = false, useable = true, max = 15 }
itemList["battery-acid"] = {name = "battery-acid", id = "battery-acid", itemId = "battery-acid", label = "BATTERY ACID" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Battery acid.", closeonuse = false, useable = true, max = 15 }
itemList["blowpipe"] = {name = "blowpipe", id = "blowpipe", itemId = "blowpipe", label = "TORCHES" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Torches", closeonuse = false, useable = true, max = 10 }
itemList["blueberry_fruit"] = {name = "blueberry_fruit", id = "blueberry_fruit", itemId = "blueberry_fruit", label = "BLUEBERRIES" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Blueberries", closeonuse = false, useable = true, max = 60 }
itemList["blueberry_package"] = {name = "blueberry_package", id = "blueberry_package", itemId = "blueberry_package", label = "BLUEBERRY PACKAGE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Packages of blueberries", closeonuse = false, useable = true, max = -1 }
itemList["blueberry_seed"] = {name = "blueberry_seed", id = "blueberry_seed", itemId = "blueberry_seed", label = "BLUEBERRY SEED" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Blueberry seeds", closeonuse = false, useable = true, max = 50 }
itemList["bodybandage"] = {name = "bodybandage", id = "bodybandage", itemId = "bodybandage", label = "BODY BANDAGE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Body bandage", closeonuse = false, useable = true, max = 5 }
itemList["bottle"] = {name = "bottle", id = "bottle", itemId = "bottle", label = "EMPTY BOTTLE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Empty bottle.", closeonuse = false, useable = true, max = -1 }
itemList["c4"] = {name = "c4", id = "c4", itemId = "c4", label = "C4" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Get into those hard to reach places.", closeonuse = false, useable = true, max = 5 }
itemList["carbon_piece"] = {name = "carbon_piece", id = "carbon_piece", itemId = "carbon_piece", label = "COAL ORE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Raw coal ore.", closeonuse = false, useable = true, max = 60 }
itemList["cigarett"] = {name = "cigarett", id = "cigarett", itemId = "cigarett", label = "CIGERETTE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Take the edge off.", closeonuse = false, useable = true, max = 20 }
itemList["citizenid"] = {name = "citizenid", id = "citizenid", itemId = "citizenid", label = "ID CARD" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "You are who you say you are.", closeonuse = false, useable = true, max = 1 }
itemList["clamp"] = {name = "clamp", id = "clamp", itemId = "clamp", label = "VEHICLE CLAMP" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Keep the car from going anywhere.", closeonuse = false, useable = true, max = 5 }
itemList["clamp_key"] = {name = "clamp_key", id = "clamp_key", itemId = "clamp_key", label = "CLAMP KEY" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Unlock the vehicle clamp.", closeonuse = false, useable = true, max = 1 }
itemList["clip"] = {name = "clip", id = "clip", itemId = "clip", label = "MAGAZINE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Backup ammo", closeonuse = false, useable = true, max = -1 }
itemList["coca_leaf"] = {name = "coca_leaf", id = "coca_leaf", itemId = "coca_leaf", label = "COCA LEAF" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "A coca leaf", closeonuse = false, useable = true, max = 175 }
itemList["coca-paste"] = {name = "coca-paste", id = "coca-paste", itemId = "coca-paste", label = "COCA PASTE 1oz" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Coca paste", closeonuse = false, useable = true, max = 10 }
itemList["coca-powder"] = {name = "coca-powder", id = "coca-powder", itemId = "coca-powder", label = "COCA POWER 1oz" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Coca powder", closeonuse = false, useable = true, max = 10 }
itemList["coke"] = {name = "coke", id = "coke", itemId = "coke", label = "COCAINE 1G" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "1 gram of cocaine", closeonuse = false, useable = true, max = 56 }
itemList["coke_pooch"] = {name = "coke_pooch", id = "coke_pooch", itemId = "coke_pooch", label = "PURE COCAINE 1G" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "1 gram of pure cocaine", closeonuse = false, useable = true, max = 28 }
itemList["contract"] = {name = "contract", id = "contract", itemId = "contract", label = "CONTRACT" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Sign it over.", closeonuse = false, useable = true, max = 5 }
itemList["copper"] = {name = "copper", id = "copper", itemId = "copper", label = "COPPER" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Copper", closeonuse = false, useable = true, max = 5 }
itemList["cutted_wood"] = {name = "cutted_wood", id = "cutted_wood", itemId = "cutted_wood", label = "CUT WOOD" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Cut wood.", closeonuse = false, useable = true, max = 20 }
itemList["dentpuller"] = {name = "dentpuller", id = "dentpuller", itemId = "dentpuller", label = "DENT PULLER" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Fix your own dents.", closeonuse = false, useable = true, max = 1 }
itemList["diamond"] = {name = "diamond", id = "diamond", itemId = "diamond", label = "DIAMOND" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "A precious gem.", closeonuse = false, useable = true, max = 50 }
itemList["dopebag"] = {name = "dopebag", id = "dopebag", itemId = "dopebag", label = "ZIPLOCK BAG" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "An empty baggie.", closeonuse = false, useable = true, max = 200 }
itemList["drugscales"] = {name = "drugscales", id = "drugscales", itemId = "drugscales", label = "SCALE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "A scale for weighing stuff.", closeonuse = false, useable = true, max = 2 }
itemList["empty-battery"] = {name = "empty-battery", id = "empty-battery", itemId = "empty-battery", label = "EMPTY BATTERY" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "A battery with no acid.", closeonuse = false, useable = true, max = 6 }
itemList["firstaid"] = {name = "firstaid", id = "firstaid", itemId = "firstaid", label = "FIRST-AID KIT" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Fixes all the ouchies.", closeonuse = false, useable = true, max = 10 }
itemList["fish"] = {name = "fish", id = "fish", itemId = "fish", label = "FISH" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Swims in the water.", closeonuse = false, useable = true, max = 10 }
itemList["fishbait"] = {name = "fishbait", id = "fishbait", itemId = "fishbait", label = "FISH BAIT" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Use this to catch fish.", closeonuse = false, useable = true, max = 25 }
itemList["fishingrod"] = {name = "fishingrod", id = "fishingrod", itemId = "fishingrod", label = "FISHING ROD" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Reel in the fish.", closeonuse = false, useable = true, max = 2 }
itemList["fixkit"] = {name = "fixkit", id = "fixkit", itemId = "fixkit", label = "FIXKIT" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Fixkit", closeonuse = false, useable = true, max = 5 }
itemList["fixtool"] = {name = "fixtool", id = "fixtool", itemId = "fixtool", label = "FIXING TOOL" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Fixing tool", closeonuse = false, useable = true, max = 6 }
itemList["flashlight"] = {name = "flashlight", id = "flashlight", itemId = "flashlight", label = "FLASHLIGHT ATTACHMENT" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Adds a flashlight to your weapon.", closeonuse = false, useable = true, max = -1 }
itemList["gauze"] = {name = "gauze", id = "gauze", itemId = "gauze", label = "GAUZE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Helps stop bleeding.", closeonuse = false, useable = true, max = 10 }
itemList["gazbottle"] = {name = "gazbottle", id = "gazbottle", itemId = "gazbottle", label = "GAS BOTTLE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "A gas bottle.", closeonuse = false, useable = true, max = 11 }
itemList["gold"] = {name = "gold", id = "gold", itemId = "gold", label = "GOLD" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "I love GOLD!", closeonuse = false, useable = true, max = 5 }
itemList["gold_piece"] = {name = "gold_piece", id = "gold_piece", itemId = "gold_piece", label = "GOLD ORE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Raw gold ore.", closeonuse = false, useable = true, max = 30 }
itemList["grip"] = {name = "grip", id = "grip", itemId = "grip", label = "GRIP" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "A grip attachment for your weapon.", closeonuse = false, useable = true, max = -1 }
itemList["gym_membership"] = {name = "gym_membership", id = "gym_membership", itemId = "gym_membership", label = "GYM MEMBERSHIP" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Can't get in without it.", closeonuse = false, useable = true, max = -1 }
itemList["heat-gun"] = {name = "heat-gun", id = "heat-gun", itemId = "heat-gun", label = "HEATGUN" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "A heatgun.", closeonuse = false, useable = true, max = 1 }
itemList["heavyarmor"] = {name = "heavyarmor", id = "heavyarmor", itemId = "heavyarmor", label = "BODY ARMOR" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "It won't make you Deadpool, but it will keep you alive longer.", closeonuse = false, useable = true, max = 3 }
itemList["highgradefemaleseed"] = {name = "highgradefemaleseed", id = "highgradefemaleseed", itemId = "highgradefemaleseed", label = "FEMALE SEED" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "A female seed.", closeonuse = false, useable = true, max = -1 }
itemList["highgradefert"] = {name = "highgradefert", id = "highgradefert", itemId = "highgradefert", label = "HIGH GRADE FERTILIZER" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Best of the best fertilizer.", closeonuse = false, useable = true, max = 4 }
itemList["highgrademaleseed"] = {name = "highgrademaleseed", id = "highgrademaleseed", itemId = "highgrademaleseed", label = "WEED SEED" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Weed seed.", closeonuse = false, useable = true, max = 50 }
itemList["hydrocodone"] = {name = "hydrocodone", id = "hydrocodone", itemId = "hydrocodone", label = "HYDROCODONE" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Eases the pain.", closeonuse = false, useable = true, max = 5 }
itemList["ing"] = {name = "ing", id = "ing", itemId = "ing", label = "INGREDIENT FOR PIZZA" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "An ingredient for pizza.", closeonuse = false, useable = true, max = -1 }
itemList["iron"] = {name = "iron", id = "iron", itemId = "iron", label = "IRON" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Iron.", closeonuse = false, useable = true, max = 5 }
itemList["iron_piece"] = {name = "iron_piece", id = "iron_piece", itemId = "iron_piece", label = "IRON ORE" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Raw iron ore.", closeonuse = false, useable = true, max = 30 }
itemList["jewels"] = {name = "jewels", id = "jewels", itemId = "jewels", label = "JEWELS" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Shiny things.", closeonuse = false, useable = true, max = -1 }
itemList["jumelles"] = {name = "jumelles", id = "jumelles", itemId = "jumelles", label = "BINOCULARS" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "See things from a distance.", closeonuse = false, useable = true, max = 1 }
itemList["keycard"] = {name = "keycard", id = "keycard", itemId = "keycard", label = "KEYCARD" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Keycard", closeonuse = false, useable = true, max = -1 }
itemList["leather"] = {name = "leather", id = "leather", itemId = "leather", label = "LEATHER" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Leather", closeonuse = false, useable = true, max = 10 }
itemList["legbrace"] = {name = "legbrace", id = "legbrace", itemId = "legbrace", label = "LEG BRACE" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "A brace for a leg.", closeonuse = false, useable = true, max = 5 }
itemList["licenseplate"] = {name = "licenseplate", id = "licenseplate", itemId = "licenseplate", label = "LICENCE PLATE" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Custom license plate.", closeonuse = false, useable = true, max = -1 }
itemList["lighter"] = {name = "lighter", id = "lighter", itemId = "lighter", label = "LIGHTER" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Fire at your fingertips.", closeonuse = false, useable = true, max = 1 }
itemList["lingot_carbon"] = {name = "lingot_carbon", id = "lingot_carbon", itemId = "lingot_carbon", label = "COAL CLUSTER" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Coal cluster.", closeonuse = false, useable = true, max = 25 }
itemList["lingot_gold"] = {name = "lingot_gold", id = "lingot_gold", itemId = "lingot_gold", label = "GOLD INGOT" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "A gold ingot.", closeonuse = false, useable = true, max = 5 }
itemList["lingot_iron"] = {name = "lingot_iron", id = "lingot_iron", itemId = "lingot_iron", label = "IRON INGOT" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "A iron ingot.", closeonuse = false, useable = true, max = 5 }
itemList["lingot_silver"] = {name = "lingot_silver", id = "lingot_silver", itemId = "lingot_silver", label = "SILVER INGOT" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "A silver ingot.", closeonuse = false, useable = true, max = 5 }
itemList["lockpick"] = {name = "lockpick", id = "lockpick", itemId = "lockpick", label = "LOCKPICK" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Who needs keys?", closeonuse = false, useable = true, max = -1 }
itemList["lowgradefemaleseed"] = {name = "lowgradefemaleseed", id = "lowgradefemaleseed", itemId = "lowgradefemaleseed", label = "LOWGRADE FEMALE SEED" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "A lowgrade female seed", closeonuse = false, useable = true, max = -1 }
itemList["lowgradefert"] = {name = "lowgradefert", id = "lowgradefert", itemId = "lowgradefert", label = "PLANT FERTILIZER" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Fertilizer to help plants grow.", closeonuse = false, useable = true, max = 5 }
itemList["lowgrademaleseed"] = {name = "lowgrademaleseed", id = "lowgrademaleseed", itemId = "lowgrademaleseed", label = "WEED SEED" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "A weed seed.", closeonuse = false, useable = true, max = -1 }
itemList["medikit"] = {name = "medikit", id = "medikit", itemId = "medikit", label = "MEDIKIT" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "A medikit.", closeonuse = false, useable = true, max = 5 }
itemList["medkit"] = {name = "medkit", id = "medkit", itemId = "medkit", label = "MEDKIT" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "A medkit.", closeonuse = false, useable = true, max = 5 }
itemList["meth"] = {name = "meth", id = "meth", itemId = "meth", label = "METH 1G" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "1 gram of meth.", closeonuse = false, useable = true, max = 40 }
itemList["meth_pooch"] = {name = "meth_pooch", id = "meth_pooch", itemId = "meth_pooch", label = "BAG OF METH (28G)" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "28 gram bag of meth.", closeonuse = false, useable = true, max = 15 }
itemList["mgAmmo"] = {name = "mgAmmo", id = "mgAmmo", itemId = "mgAmmo", label = "MACHING GUN AMMO" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Ammo for a machine gun", closeonuse = false, useable = true, max = 5 }
itemList["morphine"] = {name = "morphine", id = "morphine", itemId = "morphine", label = "MORPHINE" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "The good drugs.", closeonuse = false, useable = true, max = 5 }
itemList["neckbrace"] = {name = "neckbrace", id = "neckbrace", itemId = "neckbrace", label = "NECK BRACE" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Keeps the neck safe.", closeonuse = false, useable = true, max = 5 }
itemList["nitrocannister"] = {name = "nitrocannister", id = "nitrocannister", itemId = "nitrocannister", label = "NOS" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "A little extra boost for your vehicle.", closeonuse = false, useable = true, max = 1 }
itemList["notepad"] = {name = "notepad", id = "notepad", itemId = "notepad", label = "NOTEPAD" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Write it down for later.", closeonuse = false, useable = true, max = 10 }
itemList["opium"] = {name = "opium", id = "opium", itemId = "opium", label = "OPIUM (1G)" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "1 gram of opium.", closeonuse = false, useable = true, max = 40 }
itemList["opium_pooch"] = {name = "opium_pooch", id = "opium_pooch", itemId = "opium_pooch", label = "BAG OF OPIUM (28G)" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "28 grams of opium.", closeonuse = false, useable = true, max = 15 }
itemList["oxycutter"] = {name = "oxycutter", id = "oxycutter", itemId = "oxycutter", label = "PLASMA TORCH" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Cuts through almost anything.", closeonuse = false, useable = true, max = -1 }
itemList["pacificidcard"] = {name = "pacificidcard", id = "pacificidcard", itemId = "pacificidcard", label = "PACIFIC ID" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "An id for Pacific Bank.", closeonuse = false, useable = true, max = -1 }
itemList["packaged_chicken"] = {name = "packaged_chicken", id = "packaged_chicken", itemId = "packaged_chicken", label = "PACKAGED CHICKEN" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "A package of chicken", closeonuse = false, useable = true, max = 20 }
itemList["packaged_pig"] = {name = "packaged_pig", id = "packaged_pig", itemId = "packaged_pig", label = "PACKAGED PIG" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "A package of pork", closeonuse = false, useable = true, max = 20 }
itemList["packaged_plank"] = {name = "packaged_plank", id = "packaged_plank", itemId = "packaged_plank", label = "PACKED WOOD" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "A pack of wood", closeonuse = false, useable = true, max = 40 }
itemList["pAmmo"] = {name = "pAmmo", id = "pAmmo", itemId = "pAmmo", label = "PISTOL AMMO" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Ammo for a pistol.", closeonuse = false, useable = true, max = 5 }
itemList["pine_processed"] = {name = "pine_processed", id = "pine_processed", itemId = "pine_processed", label = "PACKAGED WOOD" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "A package of wood.", closeonuse = false, useable = true, max = 10 }
itemList["pine_wood"] = {name = "pine_wood", id = "pine_wood", itemId = "pine_wood", label = "WOOD" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Wood", closeonuse = false, useable = true, max = 50 }
itemList["phone"] = {name = "phone", id = "phone", itemId = "phone", label = "PHONE" , rare = false, weight = 3, canRemove = true, isWeapon = false, description = "Phone", closeonuse = true, useable = false, max = 2 }
itemList["purifiedwater"] = {name = "purifiedwater", id = "purifiedwater", itemId = "purifiedwater", label = "PURIFIED WATER" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "The purest of water", closeonuse = false, useable = true, max = 3 }
itemList["radio"] = {name = "radio", id = "radio", itemId = "radio", label = "RADIO" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "A radio to communicate with others.", closeonuse = false, useable = true, max = 5 }
itemList["repairkit"] = {name = "repairkit", id = "repairkit", itemId = "repairkit", label = "REPAIR KIT" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Fixes some minor issues with a vehicle.", closeonuse = true, useable = true, max = 3 }
itemList["ring"] = {name = "ring", id = "ring", itemId = "ring", label = "RING" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Must have liked it.", closeonuse = false, useable = true, max = -1 }
itemList["rolex"] = {name = "rolex", id = "rolex", itemId = "rolex", label = "ROLEX" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "High fashion watch.", closeonuse = false, useable = true, max = -1 }
itemList["rose"] = {name = "rose", id = "rose", itemId = "rose", label = "ROSE" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Do you accept it?", closeonuse = false, useable = true, max = -1 }
itemList["scubba"] = {name = "scubba", id = "scubba", itemId = "scubba", label = "SCUBBA GEAR" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Unda the sea.", closeonuse = false, useable = true, max = 15 }
itemList["sgAmmo"] = {name = "sgAmmo", id = "sgAmmo", itemId = "sgAmmo", label = "SHOTGUN SHELLS" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Ammo for a shotgun.", closeonuse = false, useable = true, max = 5 }
itemList["shark"] = {name = "shark", id = "shark", itemId = "shark", label = "SHARK" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "It's like JAWS.", closeonuse = false, useable = true, max = -1 }
itemList["shotgun_shells"] = {name = "shotgun_shells", id = "shotgun_shells", itemId = "shotgun_shells", label = "SHOTGUN SHELLS" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Ammo for a shotgun.", closeonuse = false, useable = true, max = 20 }
itemList["silencer"] = {name = "silencer", id = "silencer", itemId = "silencer", label = "SILENCER" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Assassins best friend.", closeonuse = false, useable = true, max = -1 }
itemList["silver_piece"] = {name = "silver_piece", id = "silver_piece", itemId = "silver_piece", label = "SILVER ORE" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Raw silver ore.", closeonuse = false, useable = true, max = 30 }
itemList["slaughtered_chicken"] = {name = "slaughtered_chicken", id = "slaughtered_chicken", itemId = "slaughtered_chicken", label = "DEAD CHICKEN" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Dead chicken.", closeonuse = false, useable = true, max = 20 }
itemList["slaughtered_pig"] = {name = "slaughtered_pig", id = "slaughtered_pig", itemId = "slaughtered_pig", label = "DEAD PIG" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Dead pig.", closeonuse = false, useable = true, max = 20 }
itemList["sulf-acid"] = {name = "sulf-acid", id = "sulf-acid", itemId = "sulf-acid", label = "SULPHURIC ACID 10L" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "10 liters of sulphuric acid.", closeonuse = false, useable = true, max = 4 }
itemList["teeth-powder"] = {name = "teeth-powder", id = "teeth-powder", itemId = "teeth-powder", label = "TEETHING POWDER" , rare = false, weight = 5, canRemove = true, isWeapon = false, description = "Teething powder", closeonuse = false, useable = true, max = 10 }
itemList["thermite"] = {name = "thermite", id = "thermite", itemId = "thermite", label = "THERMITE" , rare = true, weight = 1, canRemove = true, isWeapon = false, description = "Can melt through almost anything.", closeonuse = false, useable = true, max = 1 }
itemList["tomato_fruit"] = {name = "tomato_fruit", id = "tomato_fruit", itemId = "tomato_fruit", label = "TOMATO" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Is it a fruit or vegetable?", closeonuse = false, useable = true, max = 60 }
itemList["tomato_package"] = {name = "tomato_package", id = "tomato_package", itemId = "tomato_package", label = "PACKED TOMATOS" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Packaged tomatos.", closeonuse = false, useable = true, max = -1 }
itemList["tomato_seed"] = {name = "tomato_seed", id = "tomato_seed", itemId = "tomato_seed", label = "TOMATO SEED" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Tomato seeds.", closeonuse = false, useable = true, max = 50 }
itemList["trimmedweed"] = {name = "trimmedweed", id = "trimmedweed", itemId = "trimmedweed", label = "TRIMMED WEED" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Weed trimmings.", closeonuse = false, useable = true, max = -1 }
itemList["tuning_laptop"] = {name = "tuning_laptop", id = "tuning_laptop", itemId = "tuning_laptop", label = "TUNER LAPTOP" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Fine turn a vehicle.", closeonuse = true, useable = true, max = 1 }
itemList["turtle"] = {name = "turtle", id = "turtle", itemId = "turtle", label = "SEA TURTLE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "A sea turtle.", closeonuse = false, useable = true, max = 3 }
itemList["turtlebait"] = {name = "turtlebait", id = "turtlebait", itemId = "turtlebait", label = "TURTLE BAIT" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Used to catch a sea turtle.", closeonuse = false, useable = true, max = 10 }
itemList["tyrekit"] = {name = "tyrekit", id = "tyrekit", itemId = "tyrekit", label = "TIRE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Fix a flat.", closeonuse = false, useable = true, max = 2 }
itemList["umbrella"] = {name = "umbrella", id = "umbrella", itemId = "umbrella", label = "UMBRELLA" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Stay dry in the rain.", closeonuse = false, useable = true, max = -1 }
itemList["vicodin"] = {name = "vicodin", id = "vicodin", itemId = "vicodin", label = "VICODIN" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Helps to ease the pain.", closeonuse = false, useable = true, max = 5 }
itemList["watch"] = {name = "watch", id = "watch", itemId = "watch", label = "WATCH" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "What time is it?", closeonuse = false, useable = true, max = -1 }
itemList["wateringcan"] = {name = "wateringcan", id = "wateringcan", itemId = "wateringcan", label = "WATERING CAN" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Waters the plants.", closeonuse = false, useable = true, max = 1 }
itemList["weed"] = {name = "weed", id = "weed", itemId = "weed", label = "JOINT" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Relieve some stress.", closeonuse = false, useable = true, max = 40 }
itemList["weed_pooch"] = {name = "weed_pooch", id = "weed_pooch", itemId = "weed_pooch", label = "BAG OF WEED 28G" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "28 gram bag of weed.", closeonuse = false, useable = true, max = 15 }
itemList["wood"] = {name = "wood", id = "wood", itemId = "wood", label = "WOOD" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Wood", closeonuse = false, useable = true, max = 20 }
itemList["wool"] = {name = "wool", id = "wool", itemId = "wool", label = "WOOL" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Wool", closeonuse = false, useable = true, max = 40 }
itemList["wrench"] = {name = "wrench", id = "wrench", itemId = "wrench", label = "WRENCH" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Fixes leaks", closeonuse = false, useable = true, max = 1 }
itemList["yusuf"] = {name = "yusuf", id = "yusuf", itemId = "yusuf", label = "GOLD SKIN" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Fear the golden gun.", closeonuse = false, useable = true, max = -1 }

--Misc
itemList["Importinsurance"] = {name = "Importinsurance", id = "Importinsurance", itemId = "Importinsurance", label = "IMPORT INSURANCE" , rare = false, weight = 1, canRemove = true, isWeapon = false, description = "Protecting your import since 2017.", closeonuse = false, useable = true, max = 1 }





